### PR TITLE
Automate the existing deployment process

### PR DESCRIPTION
**Pull request by shtukas**

### CODE REVIEW

**Comment by aug24** [comment]
Reluctantly approved, until we can do anything better!

**Comment by shtukas** [comment]
Tested locally and successfully created `inspector-lambda-0.5.0-SNAPSHOT.jar` at the right location.

**Comment by shtukas** [comment]
@aug24

**Comment by aug24** [comment]
+1 with changes as discussed.

**Comment by shtukas** [comment]
@aug24 Updated as discussed. Merging now.

**Pull request merged**
